"""Report generation — converts markdown audit reports
to DOCX and PDF formats with professional formatting.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from pathlib import Path

from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)

from app.config import settings

logger = logging.getLogger(__name__)

# Severity colors
SEVERITY_COLORS = {
    "critical": RGBColor(220, 53, 69),   # Red
    "warning": RGBColor(255, 193, 7),     # Amber
    "info": RGBColor(13, 110, 253),       # Blue
}

PDF_SEVERITY_COLORS = {
    "critical": colors.HexColor("#DC3545"),
    "warning": colors.HexColor("#FFC107"),
    "info": colors.HexColor("#0D6EFD"),
}


def generate_docx_report(
    report_markdown: str,
    company_name: str,
    job_id: str,
    findings_data: dict | None = None,
) -> str:
    """Generate a DOCX report from markdown content.

    Args:
        report_markdown: The markdown report text
        company_name: Company name for the title
        job_id: Audit job ID
        findings_data: Optional structured findings for tables

    Returns:
        Path to the generated DOCX file.
    """
    settings.ensure_dirs()
    output_path = settings.report_dir / f"{job_id}_audit_report.docx"

    doc = Document()

    # ── Page setup ────────────────────────────────────────────────────────
    section = doc.sections[0]
    section.page_height = Cm(29.7)
    section.page_width = Cm(21.0)
    section.top_margin = Cm(2.5)
    section.bottom_margin = Cm(2.5)

    # ── Title ─────────────────────────────────────────────────────────────
    title = doc.add_heading("FORECAST — Financial Model Audit", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(f"{company_name} | {datetime.now(timezone.utc).strftime('%B %d, %Y')}")
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(108, 117, 125)

    doc.add_paragraph()  # spacer

    # ── Parse markdown and add content ────────────────────────────────────
    _markdown_to_docx(doc, report_markdown)

    # ── Add findings tables if structured data available ───────────────────
    if findings_data:
        _add_findings_tables(doc, findings_data)

    # ── Footer ────────────────────────────────────────────────────────────
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer.add_run(f"Generated by FORECAST Agentic Auditor | Job ID: {job_id}")
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(173, 181, 189)

    doc.save(str(output_path))
    logger.info(f"DOCX report saved: {output_path}")
    return str(output_path)


def generate_pdf_report(
    report_markdown: str,
    company_name: str,
    job_id: str,
    findings_data: dict | None = None,
) -> str:
    """Generate a PDF report from markdown content.

    Args:
        report_markdown: The markdown report text
        company_name: Company name for the title
        job_id: Audit job ID
        findings_data: Optional structured findings for tables

    Returns:
        Path to the generated PDF file.
    """
    settings.ensure_dirs()
    output_path = settings.report_dir / f"{job_id}_audit_report.pdf"

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    styles.add(ParagraphStyle(
        name='ReportTitle',
        parent=styles['Title'],
        fontSize=24,
        spaceAfter=6,
        textColor=colors.HexColor("#1a1a2e"),
    ))
    styles.add(ParagraphStyle(
        name='ReportSubtitle',
        parent=styles['Normal'],
        fontSize=12,
        textColor=colors.HexColor("#6c757d"),
        alignment=1,  # Center
        spaceAfter=20,
    ))
    styles.add(ParagraphStyle(
        name='SectionHead',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor("#16213e"),
        spaceBefore=16,
        spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        name='Finding',
        parent=styles['Normal'],
        fontSize=10,
        leftIndent=20,
        spaceBefore=4,
        spaceAfter=4,
    ))

    elements = []

    # ── Title ─────────────────────────────────────────────────────────────
    elements.append(Paragraph("FORECAST — Financial Model Audit", styles['ReportTitle']))
    elements.append(Paragraph(
        f"{company_name} | {datetime.now(timezone.utc).strftime('%B %d, %Y')}",
        styles['ReportSubtitle']
    ))
    elements.append(Spacer(1, 20))

    # ── Parse markdown and add content ────────────────────────────────────
    _markdown_to_pdf(elements, report_markdown, styles)

    # ── Footer ────────────────────────────────────────────────────────────
    elements.append(Spacer(1, 30))
    elements.append(Paragraph(
        f"Generated by FORECAST Agentic Auditor | Job ID: {job_id}",
        ParagraphStyle(name='Footer', parent=styles['Normal'],
                       fontSize=8, textColor=colors.HexColor("#adb5bd"), alignment=1)
    ))

    doc.build(elements)
    logger.info(f"PDF report saved: {output_path}")
    return str(output_path)


# ── Markdown → DOCX conversion ───────────────────────────────────────────────

def _markdown_to_docx(doc: Document, markdown: str):
    """Simple markdown to DOCX conversion."""
    lines = markdown.split("\n")

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue

        # Headings
        if stripped.startswith("# "):
            doc.add_heading(stripped[2:], level=1)
        elif stripped.startswith("## "):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith("### "):
            doc.add_heading(stripped[4:], level=3)
        # Table rows
        elif stripped.startswith("|"):
            # Accumulate table rows and add as table
            # (simplified: just add as paragraph for now)
            _add_line_as_paragraph(doc, stripped)
        # List items
        elif stripped.startswith("- "):
            _add_list_item(doc, stripped[2:])
        # Block quotes / warnings
        elif stripped.startswith("> "):
            p = doc.add_paragraph(stripped[2:])
            p.style = doc.styles['Intense Quote'] if 'Intense Quote' in [s.name for s in doc.styles] else None
        # Normal paragraph
        else:
            _add_line_as_paragraph(doc, stripped)


def _add_line_as_paragraph(doc: Document, text: str):
    """Add a line as a paragraph with basic bold/italic formatting."""
    p = doc.add_paragraph()
    # Simple bold handling
    parts = re.split(r'(\*\*[^*]+\*\*)', text)
    for part in parts:
        if part.startswith("**") and part.endswith("**"):
            run = p.add_run(part[2:-2])
            run.bold = True
        else:
            p.add_run(part)


def _add_list_item(doc: Document, text: str):
    """Add a bullet list item with severity coloring."""
    p = doc.add_paragraph(style='List Bullet')

    # Check for severity markers
    for severity, color in SEVERITY_COLORS.items():
        marker = f"[{severity.upper()}]"
        if marker in text:
            run = p.add_run(marker + " ")
            run.font.color.rgb = color
            run.bold = True
            text = text.replace(marker, "").strip()
            break

    p.add_run(text)


def _add_findings_tables(doc: Document, findings_data: dict):
    """Add structured findings as formatted tables."""
    if "assumptions" in findings_data and findings_data["assumptions"]:
        doc.add_heading("Assumption Benchmark Table", level=2)
        assumptions = findings_data["assumptions"]

        table = doc.add_table(rows=1, cols=5)
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        headers = ["Metric", "Value", "Unit", "Verdict", "Benchmark Range"]
        for i, header in enumerate(headers):
            table.rows[0].cells[i].text = header

        for a in assumptions:
            row = table.add_row()
            row.cells[0].text = str(a.get("name", ""))
            row.cells[1].text = str(a.get("value", ""))
            row.cells[2].text = str(a.get("unit", ""))
            row.cells[3].text = str(a.get("benchmark_verdict", "—"))
            row.cells[4].text = str(a.get("benchmark_range", "N/A"))


# ── Markdown → PDF conversion ────────────────────────────────────────────────

def _markdown_to_pdf(elements: list, markdown: str, styles):
    """Simple markdown to PDF elements conversion."""
    lines = markdown.split("\n")

    for line in lines:
        stripped = line.strip()
        if not stripped:
            elements.append(Spacer(1, 6))
            continue

        if stripped.startswith("# "):
            elements.append(Paragraph(stripped[2:], styles['Heading1']))
        elif stripped.startswith("## "):
            elements.append(Paragraph(stripped[3:], styles['SectionHead']))
        elif stripped.startswith("### "):
            elements.append(Paragraph(stripped[4:], styles['Heading3']))
        elif stripped.startswith("- "):
            # Format with bullet
            text = stripped[2:]
            # Add severity coloring
            for sev, color in PDF_SEVERITY_COLORS.items():
                marker = f"[{sev.upper()}]"
                if marker in text:
                    text = text.replace(
                        marker,
                        f'<font color="{color.hexval()}">{marker}</font>'
                    )
                    break
            elements.append(Paragraph(f"• {text}", styles['Finding']))
        elif stripped.startswith("|") and not stripped.startswith("|---"):
            # Skip table formatting rows
            if all(c in "|-: " for c in stripped):
                continue
            # Table row → paragraph (simplified)
            clean = stripped.replace("|", " | ").strip()
            elements.append(Paragraph(clean, styles['Normal']))
        elif stripped.startswith("> "):
            elements.append(Paragraph(
                f"<i>{stripped[2:]}</i>",
                ParagraphStyle(name='BlockQuote', parent=styles['Normal'],
                               leftIndent=30, textColor=colors.HexColor("#6c757d"))
            ))
        else:
            # Bold text handling
            text = re.sub(r'\*\*([^*]+)\*\*', r'<b>\1</b>', stripped)
            elements.append(Paragraph(text, styles['Normal']))
